[DEAFULTGP]
Name=通达信报价
GPINDEX_VAR1=38
GPINDEX_VAR2=43
UnitNum=2
CmdNum=1
IsFixed=0
GPINDEX_VAR3=160
GPINDEX_VAR4=170
[STEP0]
SplitWhich=-1
UnitType=HQGRID_UNIT
UnitStyle=HQGRID_ALL
HowToSplit=0
SplitRatio=100
ShowGpNo=2
IsContrallUnit=1
IsLocked=0
FixedWidth=0
FixedHeight=0
GPType=6
BlockFlag=-1
[STEP1]
SplitWhich=0
UnitType=HQGRID_UNIT
UnitStyle=HQGRID_ZX
HowToSplit=-1
SplitRatio=28
ShowGpNo=1
IsContrallUnit=1
IsLocked=0
FixedWidth=0
FixedHeight=0
GPType=13
BlockFlag=-1
